#ifndef OPERACIONES_CON_QSTRINGS_GLOBAL_H
#define OPERACIONES_CON_QSTRINGS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPERACIONES_CON_QSTRINGS_LIBRARY)
#  define OPERACIONES_CON_QSTRINGSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPERACIONES_CON_QSTRINGSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERACIONES_CON_QSTRINGS_GLOBAL_H
